config/routes.rb
Ncomtter::Application.routes.draw do
  resources :users unless Rails.env.production?

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  delete "/logout" => "sessions#destroy", :as => :logout

  get "/following" => "following#index"
  get "/icons" => "icons#index"

  root :to => 'index#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :nickname, :provider, :secret, :token, :uid

  def self.from_omniauth(auth)
    if (user = find_by_provider_and_uid(auth["provider"], auth["uid"]))
      user.nickname = auth["info"]["nickname"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
      user.save! if user.changed?
    else
      create_with_omniauth(auth)
    end
    user
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.nickname = auth["info"]["nickname"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
    end
  end

  def following(cursor = -1)
    twitter_client.following({:count => 200, :cursor => cursor})
  end

  private

  def twitter_client
    @client ||= ::Twitter::Client.new({
      :consumer_key => ENV["TWITTER_KEY"],
      :consumer_secret => ENV["TWITTER_SECRET"],
      :oauth_token => self.token,
      :oauth_token_secret => self.secret,
    })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def login_required
    redirect_to :root unless current_user
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  before_filter :login_required

  def index
    @cursor = current_user.following(params[:cursor])
  end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_filter :login_required

  def index
    @cursor = current_user.following(params[:cursor])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id

    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/following_helper.rb
module FollowingHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/following/index.html.erb
<h1>Following</h1>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Following</th>
    <th>Followers</th>
    <th>Last Tweeted At</th>
  </tr>

<% @cursor.attrs[:users].each do |user| %>
  <tr>
    <td><%= image_tag(url_for(user[:profile_image_url]), :size => "48x48", :alt => user[:screen_name]) %></td>
    <td><%= user[:screen_name] %></td>
    <td><%= user[:friends_count] %></td>
    <td><%= user[:followers_count] %></td>
    <td><%= "#{time_ago_in_words(user[:status][:created_at])} ago" if user[:status] %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to('Next', following_path(:cursor => @cursor.next)) if @cursor.next != 0 %>

app/views/icons/index.html.erb
<h1>Icons</h1>

<% @cursor.attrs[:users].each do |user| %>
  <td><%= image_tag(url_for(user[:profile_image_url]), :size => "48x48", :alt => user[:screen_name]) %></td>
<% end %>

app/views/index/index.html.erb
<h1>Cloudn PaaS Hackathon Sample App.</h1>

<% if current_user %>
  login as:
  <%= current_user.nickname %>
  <%= link_to "log out", logout_path, :method => "delete" %>
<% else %>
  sign in:
  <%= link_to image_tag("https://raw.github.com/intridea/authbuttons/master/png/twitter_32.png"), "/auth/twitter" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ncomtter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <style type="text/css">
      body {
        padding-top: 40px;
      }
    </style>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Ncomtter</a>
          <div class="container nav-collapse">
            <% if current_user %>
              <ul class="nav">
                <li><%= link_to "Following", "/following"  %></li>
                <li><%= link_to "Icons", "/icons"  %></li>
              </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; @hamakn 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :provider, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :provider, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :uid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :uid, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nickname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nickname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :secret, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :secret, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%= model_class.human_attribute_name(:uid) %></th>
      <th><%= model_class.human_attribute_name(:nickname) %></th>
      <th><%= model_class.human_attribute_name(:token) %></th>
      <th><%= model_class.human_attribute_name(:secret) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= user.nickname %></td>
        <td><%= user.token %></td>
        <td><%= user.secret %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @user.provider %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= @user.uid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nickname) %>:</strong></dt>
  <dd><%= @user.nickname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:token) %>:</strong></dt>
  <dd><%= @user.token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:secret) %>:</strong></dt>
  <dd><%= @user.secret %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>